# Generated by Django 3.1.5 on 2021-02-03 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pinha.models
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pinha', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('phoneNumber', models.CharField(max_length=11, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=pinha.models.image_path)),
                ('background', models.ImageField(blank=True, null=True, upload_to=pinha.models.image_path)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('is_school_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.UUID('5baccaee-8a5f-44d4-b1fd-f758125cbe25'))),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FavList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('store', models.ManyToManyField(to='pinha.Store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_first_avatar_change', models.BooleanField(default=False)),
                ('is_first_review', models.BooleanField(default=False)),
                ('shared_count', models.PositiveSmallIntegerField(default=0)),
                ('is_first_save_store', models.BooleanField(default=False)),
                ('review_count', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
