# Generated by Django 3.1.5 on 2021-02-03 14:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('85f1bde3-4dbb-4651-acf8-6f8dd69bcbfa')),
        ),
    ]
